# Generated by Django 5.0.1 on 2024-03-21 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.CharField(max_length=1287)),
                ('title', models.CharField(max_length=56)),
                ('author', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('status', models.BooleanField()),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=20)),
                ('cellPhoneNumber', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rentStart', models.DateTimeField(blank=True, null=True)),
                ('rentEnd', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=25, null=True)),
                ('books', models.ManyToManyField(to='myLibrarian.book')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myLibrarian.user')),
            ],
        ),
    ]
