# Generated by Django 5.0.1 on 2024-03-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myLibrarian', '0003_alter_user_cellphonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='status',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
