# Generated by Django 5.0.1 on 2024-03-14 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myLibrarian', '0004_alter_rent_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='status',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
