# Generated by Django 5.0.1 on 2024-03-14 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myLibrarian', '0005_alter_rent_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
